# Servidor y puerto de la app
server.port=8080

# Configuración de la Base de Datos (Cambia 'db_proyecto' por el nombre de tu esquema en MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_proyecto?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=tu_contraseña_aqui

# Propiedades de Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
